## 6-е домашнее задание - Библиотека numpy

<b>Срок до 2 июня 2022г. (включительно)</b>

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring_Python_2022</b>» в github в папку "<b>homework-6</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


Морозов Евгений НПМ-бд-01-19

In [2]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [3]:
a = np.linspace(-1.3, 2.5, 65)
a

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [4]:
n = 4
b = np.tile(np.arange(1, 4), (1, n))
b

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

3.	Создайте массив первых 10 нечетных целых чисел.

In [5]:
n = 10
c = np.linspace(1, 2 * n - 1, n)   
c

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [6]:
d = np.zeros((10, 10))
d[:, 0:10:9] = 1
d[0:10:9, :] = 1
print('Рамка в массиве:', d, sep='\n', end='\n\n')

Рамка в массиве:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]



5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [7]:
g = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(g)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [8]:
def create_m(n):
    matrix = np.zeros((n, n))
    for i in range(n):
        matrix[i, :] = np.arange(0, n) + i
    return matrix

print(create_m(10))

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
 [ 7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
 [ 8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [9]:
matrix = np.array(np.arange(0, 12)).reshape(3, 4)
print('matrix', matrix, sep='\n', end='\n\n')

vector = np.array(np.arange(0, 4))
print('vector', vector, sep='\n', end='\n\n')

print('vector.dot(vector)', vector.dot(vector), sep='\n', end='\n\n')
print('matrix.dot(vector)', matrix.dot(vector), sep='\n', end='\n\n')
print('matrix.dot(matrix.T)', matrix.dot(matrix.T), sep='\n')

matrix
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

vector
[0 1 2 3]

vector.dot(vector)
14

matrix.dot(vector)
[14 38 62]

matrix.dot(matrix.T)
[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [10]:
cosx = np.cos(np.arange(0, 1.05, 0.05))
sinx = np.sin(np.arange(0, 1.05, 0.05))
h = np.concatenate((cosx, sinx))
h

array([1.        , 0.99875026, 0.99500417, 0.98877108, 0.98006658,
       0.96891242, 0.95533649, 0.93937271, 0.92106099, 0.9004471 ,
       0.87758256, 0.85252452, 0.82533561, 0.7960838 , 0.76484219,
       0.73168887, 0.69670671, 0.65998315, 0.62160997, 0.58168309,
       0.54030231, 0.        , 0.04997917, 0.09983342, 0.14943813,
       0.19866933, 0.24740396, 0.29552021, 0.34289781, 0.38941834,
       0.43496553, 0.47942554, 0.52268723, 0.56464247, 0.60518641,
       0.64421769, 0.68163876, 0.71735609, 0.75128041, 0.78332691,
       0.8134155 , 0.84147098])

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [11]:
A = (3 - (-1)) * np.random.rand(3, 5) + (-1)
A

array([[ 1.60859352e+00,  1.68002388e+00,  9.58723192e-01,
         2.47279245e+00,  1.92837369e+00],
       [ 2.72945836e+00,  4.14401530e-01, -6.27550306e-01,
         1.10568008e+00,  1.50444141e-03],
       [ 2.53591028e+00, -4.56571318e-01, -1.91764281e-01,
         1.59454485e+00,  1.89745547e+00]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [12]:
print(f'сумма всех элементов {A.sum()}')
print(f'сумма элементов по столбцам {A.sum(axis=0)}')
print(f'сумма элементов по строкам {A.sum(axis=1)}')
print(f'среднее значение по строкам {A.mean(axis=1)}')
print(f'дисперсия по строкам {A.var(axis=1)}')
print(f'стандартное отклонение по строкам {A.std(axis=1)}')

сумма всех элементов 17.651575844494424
сумма элементов по столбцам [6.87396216 1.63785409 0.1394086  5.17301739 3.8273336 ]
сумма элементов по строкам [8.64850673 3.62349411 5.379575  ]
среднее значение по строкам [1.72970135 0.72469882 1.075915  ]
дисперсия по строкам [0.24063947 1.32241595 1.40620339]
стандартное отклонение по строкам [0.49055017 1.14996346 1.18583447]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [13]:
for i in range(len(A)):
    A[i, :] = (A[i, :] - A.mean(axis=1)[i]) / A.std(axis=1)[i]
A

array([[-0.24688163, -0.10126888, -1.57166014,  1.51481163,  0.40499903],
       [ 1.74332456, -0.26983231, -1.17590617,  0.33129858, -0.62888466],
       [ 1.23119653, -1.29232735, -1.06901875,  0.43735434,  0.69279523]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [14]:
A = np.array([[1, 2, 3],
              [-1, 10, 10000],
              [-1000, 0, 1001]])
ind = A[:, 2].argsort()
A[ind]

array([[    1,     2,     3],
       [-1000,     0,  1001],
       [   -1,    10, 10000]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [15]:
A = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [15, 12, 11, 113]])

B = A.T.dot(A)
C = A.dot(A.T)
print('B = A.T.dot(A)', B, sep='\n')
print()
print('C = A.dot(A.T)', C, sep='\n')

B = A.T.dot(A)
[[  251   212   203  1739]
 [  212   184   180  1412]
 [  203   180   179  1311]
 [ 1739  1412  1311 12849]]

C = A.dot(A.T)
[[   30    70   524]
 [   70   174  1128]
 [  524  1128 13259]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [16]:
print(f'сумма диагональных элементов для В = {np.diag(B).sum()}')
print(f'сумма диагональных элементов для C = {np.diag(C).sum()}')

сумма диагональных элементов для В = 13463
сумма диагональных элементов для C = 13463


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [17]:
print('A:', f'det = {np.linalg.det(B)}',
      f'rg = {np.linalg.matrix_rank(B)}', f'с.з. = {np.linalg.eig(B)[0]}', sep='\n')
print()
print('B:', f'det = {np.linalg.det(B)}', 
      f'rg = {np.linalg.matrix_rank(B)}', f'с.з. = {np.linalg.eig(B)[0]}', sep='\n')
print()
print('C:', f'det = {np.linalg.det(C)}', 
      f'rg = {np.linalg.matrix_rank(C)}', f'с.з. = {np.linalg.eig(C)[0]}', sep='\n')

A:
det = 3.7243808037597826e-09
rg = 3
с.з. = [1.33764209e+04 8.56669313e+01 9.12121960e-01 6.50171779e-14]

B:
det = 3.7243808037597826e-09
rg = 3
с.з. = [1.33764209e+04 8.56669313e+01 9.12121960e-01 6.50171779e-14]

C:
det = 1045215.9999999979
rg = 3
с.з. = [1.33764209e+04 9.12121960e-01 8.56669313e+01]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [20]:
np.random.seed(1032181583)
print(f'вариант {np.random.randint(10)}')

вариант 0


In [21]:
def f(x):
    return (x + 1) / (x - 2)

def p(f, a, b, sh):
    x = np.linspace(a, b - sh, int((b - a) / sh))
    y = sh * f(x) 
    return np.sum(y)

def t(f, a, b, sh):
    x = np.linspace(a, b, int((b - a) / sh) + 1)
    y = f(x[0]) + 2 * np.sum(f(x[1:-1])) + f(x[-1])
    return y * sh / 2

def s(f, a, b, sh):
    x = np.linspace(a, b, int((b - a) / sh) + 1)
    y = f(x[0]) + 4 * np.sum(f(x[1:-1:2])) + 2 * np.sum(f(x[2:-1:2])) + f(x[-1])
    return y * sh / 3

print('Метод прямоугольников:', p(f, 3, 4, 0.01))
print('Метод трапеций:', t(f, 3, 4, 0.001))
print('Метод Симпсона:', s(f, 3, 4, 0.0001))

Метод прямоугольников: 3.086960291445473
Метод трапеций: 3.0794417291798126
Метод Симпсона: 3.079441541679836
